application: live-count
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on
- appstats: on

admin_console:
  pages:
  
inbound_services:
- warmup

handlers:
- url: /livecount/counter_admin
  script: livecount/counter_admin.py
  login: admin
  
- url: /livecount/get_counter
  script: livecount/counter_admin.py
  login: admin
  
- url: /write_behind_counter/worker
  script: livecount/write_behind_counter.py
  login: admin 
  
- url: /livecount/clear_entire_cache
  script: livecount/write_behind_counter.py
  login: admin
  
- url: /livecount/writeback_all_counters
  script: livecount/write_behind_counter.py
  login: admin
  
- url: /livecount/get_count
  script: livecount/write_behind_counter.py
  login: admin


  